{
  "formatVersion": "1.1",
  "component": {
    "group": "earth.terrarium",
    "module": "cloche",
    "version": "0.15.1-dust",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "cloche-0.15.1-dust.jar",
          "url": "cloche-0.15.1-dust.jar",
          "size": 559980,
          "sha512": "3c14eeb0b9af725e945d29b4360fa990cf07988d4cb57634c534b45400259316e0642f4ccc3217e4ef5132bbbed052df3fea7bf3b848f8a543ff0a2c52b305e4",
          "sha256": "417c515234bb7ab766e0666fc9a81239dfb79586769736d8f29e080b7fe5d59d",
          "sha1": "25515f401cec81eb29256522cb2c10146ca4026b",
          "md5": "d090644b95bd9b694cbec3b8d27d2870"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-forge",
          "version": {
            "requires": "0.6.5"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-fabric",
          "version": {
            "requires": "0.6.6"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.4"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.6.7"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-decompiler",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "class-extensions-gradle-plugin",
          "version": {
            "requires": "1.0.11"
          }
        },
        {
          "group": "net.msrandom",
          "module": "jvm-virtual-source-sets",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "net.msrandom",
          "module": "classpath-api-stubs",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "net.peanuuutz.tomlkt",
          "module": "tomlkt",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-toml",
          "version": {
            "requires": "5.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "cloche-0.15.1-dust.jar",
          "url": "cloche-0.15.1-dust.jar",
          "size": 559980,
          "sha512": "3c14eeb0b9af725e945d29b4360fa990cf07988d4cb57634c534b45400259316e0642f4ccc3217e4ef5132bbbed052df3fea7bf3b848f8a543ff0a2c52b305e4",
          "sha256": "417c515234bb7ab766e0666fc9a81239dfb79586769736d8f29e080b7fe5d59d",
          "sha1": "25515f401cec81eb29256522cb2c10146ca4026b",
          "md5": "d090644b95bd9b694cbec3b8d27d2870"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.15.1-dust-javadoc.jar",
          "url": "cloche-0.15.1-dust-javadoc.jar",
          "size": 261,
          "sha512": "90f41ad5bcca4294f00ad990d46001d38895fab2cb19daa8a4c649f92548923ded7a0c76c31a261e5383f51ad6a556bea37b87208465d2c371badbd270c996f1",
          "sha256": "33add428389909112c19ced81f83516018d9841d5a7c4c9e335e68da2b493e9c",
          "sha1": "254250981508112fe083160f4c11032ebad8a919",
          "md5": "0ec35b8d59794bbe26def5e00f0661b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.15.1-dust-sources.jar",
          "url": "cloche-0.15.1-dust-sources.jar",
          "size": 79078,
          "sha512": "df4f1df1ad9723b39efa7ec11f77deed4c69bc60c4119233dd6b5d8b26e49d5b9bbccab8ab2e348081c5541c4323ebbdf56ad366acd4ceb4072f5e888ac77521",
          "sha256": "efa12f0fa7fac84d2a7fd9c885744c39af9db74e6333eccab12ecde87de5f1bd",
          "sha1": "0522c8a9a147d98b76c75e927af88dcb5d6cf401",
          "md5": "43ae96d4afcc0683e8a137fcb92c3095"
        }
      ]
    }
  ]
}
