{
  "formatVersion": "1.1",
  "component": {
    "group": "earth.terrarium",
    "module": "cloche",
    "version": "0.15.1-dust",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "cloche-0.15.1-dust.jar",
          "url": "cloche-0.15.1-dust.jar",
          "size": 559913,
          "sha512": "ccb123f39b7993c4f0d00a283cfa1905f581cffbe2b4b27f97fa45a65468b0ad2082efd00660e49d3c71fba67b242506f37855f08e418a64b4d389d68989c6cf",
          "sha256": "cffb37c5a50c2d86fb5fe6a3fb0d1308e31592b0c435dd1ce1214b8155678bed",
          "sha1": "8035fdfee0a7b61038c368168f2f6725724666fe",
          "md5": "ba9e0581c64bca144555f5c0a5ef7cfb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-forge",
          "version": {
            "requires": "0.6.5"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-fabric",
          "version": {
            "requires": "0.6.6"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.4"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.6.7"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-decompiler",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "class-extensions-gradle-plugin",
          "version": {
            "requires": "1.0.11"
          }
        },
        {
          "group": "net.msrandom",
          "module": "jvm-virtual-source-sets",
          "version": {
            "requires": "1.3.4"
          }
        },
        {
          "group": "net.msrandom",
          "module": "classpath-api-stubs",
          "version": {
            "requires": "0.1.9"
          }
        },
        {
          "group": "net.peanuuutz.tomlkt",
          "module": "tomlkt",
          "version": {
            "requires": "0.4.0"
          }
        },
        {
          "group": "org.apache.groovy",
          "module": "groovy-toml",
          "version": {
            "requires": "5.0.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.18.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "cloche-0.15.1-dust.jar",
          "url": "cloche-0.15.1-dust.jar",
          "size": 559913,
          "sha512": "ccb123f39b7993c4f0d00a283cfa1905f581cffbe2b4b27f97fa45a65468b0ad2082efd00660e49d3c71fba67b242506f37855f08e418a64b4d389d68989c6cf",
          "sha256": "cffb37c5a50c2d86fb5fe6a3fb0d1308e31592b0c435dd1ce1214b8155678bed",
          "sha1": "8035fdfee0a7b61038c368168f2f6725724666fe",
          "md5": "ba9e0581c64bca144555f5c0a5ef7cfb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.15.1-dust-javadoc.jar",
          "url": "cloche-0.15.1-dust-javadoc.jar",
          "size": 261,
          "sha512": "41d105ecf864eda9365526a41fdac4548636c2ffaf34e98dd1382497db62e5547222e16f265b8e5583400815726382b720dad33b4c2899c46e402cd574dc4125",
          "sha256": "756825e5b43409c246d659310a3fb0e23fe9307de751e02d37ca596d561b7009",
          "sha1": "a57fe37f55d1ca2fd40c757de7281a6f54457ab0",
          "md5": "8e72e6121aad43288f0d5e52e5617b52"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.15.1-dust-sources.jar",
          "url": "cloche-0.15.1-dust-sources.jar",
          "size": 79097,
          "sha512": "c7a0ef5e3b70a9b8e117803b68263ec2e8662582e376a3305f4ce486081856413288b9a0a63c2dc9167c4bc3ed7c0540d5454f15b77400612b3924b341e7facd",
          "sha256": "70d76bc9ab7280810a1fc4be0a711e95b3390fc625385294c36820d4c6338adb",
          "sha1": "6010371298215b8636570961bff36f3f2faa97bc",
          "md5": "bfc7ede701bf7e7bbfe804483e7efd7a"
        }
      ]
    }
  ]
}
