{
  "formatVersion": "1.1",
  "component": {
    "group": "earth.terrarium",
    "module": "cloche",
    "version": "0.13.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cloche-0.13.2.jar",
          "url": "cloche-0.13.2.jar",
          "size": 419196,
          "sha512": "353c7687a840ab47956e6e3c02027ff7adec6e92131284ca8d5ad3cb7e09344a4842349fd87520b9dc196700cea45a90e507853c58f96fca04dbf654c699c62a",
          "sha256": "7a8401c6329cc4267f712243f5c119be0d4365842af8b1cdbf25a1aefba28d09",
          "sha1": "17d3e41488cd2101f73a5bd03e3cdfb49cff8dc1",
          "md5": "fb2a15e4091388b3660cf268c6be224a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-core",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-forge",
          "version": {
            "requires": "0.6.5"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-fabric",
          "version": {
            "requires": "0.6.6"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-mixins",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-runs",
          "version": {
            "requires": "0.6.4"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-access-widener",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-remapper",
          "version": {
            "requires": "0.6.7"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-decompiler",
          "version": {
            "requires": "0.5.32"
          }
        },
        {
          "group": "net.msrandom",
          "module": "minecraft-codev-includes",
          "version": {
            "requires": "0.6.2"
          }
        },
        {
          "group": "net.msrandom",
          "module": "class-extensions-gradle-plugin",
          "version": {
            "requires": "1.0.11"
          }
        },
        {
          "group": "net.msrandom",
          "module": "jvm-virtual-source-sets",
          "version": {
            "requires": "1.3.3"
          }
        },
        {
          "group": "net.msrandom",
          "module": "classpath-api-stubs",
          "version": {
            "requires": "0.1.8"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "com.google.devtools.ksp.gradle.plugin",
          "version": {
            "requires": "2.1.21-2.0.2"
          }
        },
        {
          "group": "com.moandjiezana.toml",
          "module": "toml4j",
          "version": {
            "requires": "0.7.2"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-lang3",
          "version": {
            "requires": "3.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin"
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "cloche-0.13.2.jar",
          "url": "cloche-0.13.2.jar",
          "size": 419196,
          "sha512": "353c7687a840ab47956e6e3c02027ff7adec6e92131284ca8d5ad3cb7e09344a4842349fd87520b9dc196700cea45a90e507853c58f96fca04dbf654c699c62a",
          "sha256": "7a8401c6329cc4267f712243f5c119be0d4365842af8b1cdbf25a1aefba28d09",
          "sha1": "17d3e41488cd2101f73a5bd03e3cdfb49cff8dc1",
          "md5": "fb2a15e4091388b3660cf268c6be224a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.13.2-javadoc.jar",
          "url": "cloche-0.13.2-javadoc.jar",
          "size": 261,
          "sha512": "76b5a25b49628c8cfd4e395229003801a9d62fb0a69215b56d24ad749ac65ab8d5c7de816d1d066cfd6c04739d619fc8896be650a64ad76fc5905788b3004fb2",
          "sha256": "980c74b53623271cbd56f53e8cf0952aec815a12902e02e29ea1fd79773a4f3f",
          "sha1": "6ae81c19f45cb8f350c43f9c111e2bbc2601c429",
          "md5": "ac72fcf4d41eb46d51235859326bf91e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cloche-0.13.2-sources.jar",
          "url": "cloche-0.13.2-sources.jar",
          "size": 69184,
          "sha512": "ffc6fe4527f137100176736cc20a0c937614401354f1f6e6dd397ee3ea04b49e4f54dcdd55f8d110f66ae1c280f2d0878e947e0fd46212b315dddf55be6b8172",
          "sha256": "f40de0307b4e24c6d73fccbe57b044e059b15152788f1ebe5e01a7f412b983bd",
          "sha1": "fe97ade87f78cfafcb74a130596dbbd3c67c5afe",
          "md5": "4e7ea42d95b60eead47122cb47ddffbe"
        }
      ]
    }
  ]
}
